import { Inter } from "next/font/google";
import "../styles/global.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "JOJOS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  console.log("RootLayout rendered");

  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/Icon.png" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
